services:
  - type: web
    name: real-time-stock-api
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: app
    buildCommand: pip install -r app/requirements.txt
    startCommand: python main.py
