services:
  - type: web
    name: stock-backend
    runtime: python
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: FETCH_INTERVAL
        value: "900"
      - key: SYMBOLS
        value: "AAPL"
      - key: RETRAIN_THRESHOLD
        value: "0.1"
