services:
  - type: web
    name: real-time-stock-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    rootDir: app
